name: Staging Build
on:
  push:
    branches:
      - staging
jobs:
  call-build-deploy:
    uses: dictyBase/workflows/.github/workflows/composite-deploy.yaml@develop
    secrets: inherit
    with:
      app: grpc-client
      repository: ${{ github.repository }}
      ref: ${{ github.ref_name }}
      dockerfile: Dockerfile
      docker_image: grpc-client
      cluster: ${{ vars.DEV_STAGING_CLUSTER }}
      cluster_state_storage: ${{ vars.DEV_STAGING_KOPS_STATE_STORAGE }}
      stack: staging
      environment: staging
